version: '2'

services:
  proxy:
    build: ./
    networks:
      - webservice1
      - webservice2
    ports:
      - 8080:80
      - 8443:443

networks:
  webservice1:
    external:
      name: webservice1_default
  webservice2:
    external:
      name: webservice2_default
